# Generated by Django 3.1.7 on 2021-03-06 01:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0011_auto_20201222_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='f10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trader',
            name='f11',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trader',
            name='f12',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trader',
            name='f13',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trader',
            name='f14',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trader',
            name='f15',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trader',
            name='f9',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='update',
            name='update_time',
            field=models.TimeField(default=datetime.datetime(2021, 3, 6, 1, 52, 48, 110147, tzinfo=utc)),
        ),
    ]
