# Generated by Django 3.1.7 on 2021-03-17 11:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0012_auto_20210306_0722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trader',
            name='f10',
        ),
        migrations.RemoveField(
            model_name='trader',
            name='f11',
        ),
        migrations.RemoveField(
            model_name='trader',
            name='f12',
        ),
        migrations.RemoveField(
            model_name='trader',
            name='f13',
        ),
        migrations.RemoveField(
            model_name='trader',
            name='f14',
        ),
        migrations.RemoveField(
            model_name='trader',
            name='f15',
        ),
        migrations.RemoveField(
            model_name='trader',
            name='f9',
        ),
        migrations.AlterField(
            model_name='update',
            name='update_time',
            field=models.TimeField(default=datetime.datetime(2021, 3, 17, 11, 35, 30, 1441, tzinfo=utc)),
        ),
    ]
